import tkinter
from .... import windows as windows
from ..appearance_mode import CTkAppearanceModeBaseClass as CTkAppearanceModeBaseClass
from ..font import CTkFont as CTkFont
from ..image import CTkImage as CTkImage
from ..scaling import CTkScalingBaseClass as CTkScalingBaseClass
from ..theme import ThemeManager as ThemeManager
from ..utility import check_kwargs_empty as check_kwargs_empty, pop_from_dict_by_set as pop_from_dict_by_set
from typing import Any

class CTkBaseClass(tkinter.Frame, CTkAppearanceModeBaseClass, CTkScalingBaseClass):
    def __init__(self, master: Any, width: int = 0, height: int = 0, bg_color: str | tuple[str, str] = 'transparent', **kwargs) -> None: ...
    def destroy(self) -> None: ...
    def config(self, *args, **kwargs) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs) -> None: ...
    def cget(self, attribute_name: str): ...
    def bind(self, sequence=None, command=None, add=None) -> None: ...
    def unbind(self, sequence=None, funcid=None) -> None: ...
    def unbind_all(self, sequence) -> None: ...
    def bind_all(self, sequence=None, func=None, add=None) -> None: ...
    def place(self, **kwargs): ...
    def place_forget(self): ...
    def pack(self, **kwargs): ...
    def pack_forget(self): ...
    def grid(self, **kwargs): ...
    def grid_forget(self): ...
