import tkinter
from ..appearance_mode import CTkAppearanceModeBaseClass as CTkAppearanceModeBaseClass
from ..font import CTkFont as CTkFont
from ..scaling import CTkScalingBaseClass as CTkScalingBaseClass
from ..theme import ThemeManager as ThemeManager
from typing import Callable

class DropdownMenu(tkinter.Menu, CTkAppearanceModeBaseClass, CTkScalingBaseClass):
    def __init__(self, *args, min_character_width: int = 18, fg_color: str | tuple[str, str] | None = None, hover_color: str | tuple[str, str] | None = None, text_color: str | tuple[str, str] | None = None, font: tuple | CTkFont | None = None, command: Callable | None = None, values: list[str] | None = None, **kwargs) -> None: ...
    def destroy(self) -> None: ...
    def open(self, x: int | float, y: int | float): ...
    def close(self) -> None: ...
    def is_open(self) -> bool: ...
    def configure(self, **kwargs) -> None: ...
    def cget(self, attribute_name: str) -> any: ...
