RULE_NAMES = {
    "generate_uid": "UID generieren",
    "copy_target": "Kopieren aus",
    "format_date": "Datum (YYYY-MM-DD)",
    "default_value": "Standardwert",
    "static_value": "Festwert",
    "clean_plz": "PLZ (5-stellig)",
    "gender": "Geschlecht->Anrede",
    "split_street": "Nur Straße",
    "split_number": "Nur Hausnummer",
    "merge_columns": "Spalten zusammenführen",
    "lookup_ik_provider": "Krankenkasse aus IK",
    "lookup_plz_by_city": "PLZ aus Ort ergänzen",
    "lookup_city_by_plz": "Ort aus PLZ ergänzen",
    "validate_ik": "IK-Nummer prüfen",
    "validate_kvnr": "Versichertennr. prüfen",
    "validate_email": "E-Mail prüfen",
    "auto_sequence_6": "Lineare Nummerierung (6-stellig)"
}
APP_WIDTH = 1040
APP_HEIGHT = 880
FONT_TYPE = "Roboto"
LABEL_FONT_BOLD = (FONT_TYPE, 11, "bold")
LABEL_FONT = (FONT_TYPE, 11)
LARGER_LABEL_FONT_BOLD = (FONT_TYPE, 14, "bold")
SMALL_LABEL_FONT = (FONT_TYPE, 10)
SMALL_LABEL_FONT_BOLD = (FONT_TYPE, 10, "bold")
BUTTON_FONT = (FONT_TYPE, 12, "bold")
TITLE_FONT = (FONT_TYPE, 18, "bold")
BOLD_FONT = (FONT_TYPE, "bold")
OPTIONS_MENU_WIDTH = 160
MAX_CHAR_READ = 4096
RULE_BUTTON_WIDTH = 240
COL_ORANGE = "#CF8700"
COL_DARK_ORANGE = "#855600"
COL_LIGHT_GREEN = "#2FA572"
COL_GREEN = "#00B800"
COL_DARK_GREEN = "#1E7E34"
COL_DARKER_GREEN = "#145A24"
COL_LIGHT_RED = "#E57373"
COL_WHITE = "#FFFFFF"
COL_BLACK = "#000000"
COL_GRAY_20 = "#333333"
COL_GRAY_30 = "#4D4D4D"
COL_GRAY_35 = "#595959"
COL_GRAY_40 = "#666666"
COL_GRAY_45 = "#737373"
COL_GRAY_70 = "#B3B3B3"
TRANSFORMATION_DIALOG_WIDTH = 540
TRANSFORMATION_DIALOG_HEIGHT = 950
VALUE_FIELD_WIDTH = 200
ROW_VALIDATION_DIALOG_WIDTH = 980
ROW_VALIDATION_DIALOG_HEIGHT = 730
BATCH_PROCESS_BUTTON_WIDTH = 150
REPLACEMENT_INPUT_WIDTH = 180
EXTRA_FIELDS_DIALOG_WIDTH = 800
EXTRA_FIELDS_DIALOG_HEIGHT = 600
BUTTON_HEIGHT = 35
DB_FIELD_NAMES_WIDTH = 190
DROPDOWN_WIDTH = 130
VALIDATION_DIALOG_WIDTH = 850
VALIDATION_DIALOG_HEIGHT = 550
INFO_LABEL_WIDTH = 300
MANUAL_CHANGE_FIELD_WIDTH = 140
RADIO_BUTTON_LABEL_WIDTH = 90
STRING_CLEANUP_DIALOG_WIDTH = 1000
STRING_CLEANUP_DIALOG_HEIGHT = 700
REPLACEMENT_WRAP_LENGTH = 700
BUTTON_WIDTH = 120
SMALL_HEADER_WIDTH = 70
LARGE_HEADER_WIDTH = 220
CHECKBOX_LABEL_WIDTH = 50
PROCESS_BUTTON_WIDTH = 200
APP_APPEARANCE_MODE = "system" # Can be one of "light", "dark", "system".
APP_COLOR_THEME = "blue"
CHECKBOX_WIDTH = 30
HEADER_LABEL_WIDTH = 90
PADDING_XXS = 3
PADDING_XS = 5
PADDING_S = 8
PADDING_M = 10
PADDING_L = 15
PADDING_XL = 20
PADDING_XXL = 25
PADDING_XXXL = 45
AUTO_COMPLETE_DIALOG_WIDTH = 450
AUTO_COMPLETE_DIALOG_HEIGHT = 320