import tkinter

class CTkCanvas(tkinter.Canvas):
    radius_to_char_fine: dict
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def init_font_character_mapping(cls) -> None: ...
    def create_aa_circle(self, x_pos: int, y_pos: int, radius: int, angle: int = 0, fill: str = 'white', tags: str | tuple[str, ...] = '', anchor: str = ...) -> int: ...
    def coords(self, tag_or_id, *args) -> list[float]: ...
    def itemconfig(self, tag_or_id, *args, **kwargs) -> None: ...
