from ..core_rendering import CTkCanvas as CTkCanvas

class DrawEngine:
    DRAWING_METHODS: list[str]
    preferred_drawing_method: str
    def __init__(self, canvas: CTkCanvas) -> None: ...
    def set_round_to_even_numbers(self, round_width_to_even_numbers: bool = True, round_height_to_even_numbers: bool = True): ...
    def draw_background_corners(self, width: float | int, height: float | int): ...
    def draw_rounded_rect_with_border(self, width: float | int, height: float | int, corner_radius: float | int, border_width: float | int, overwrite_preferred_drawing_method: str = None) -> bool: ...
    def draw_rounded_rect_with_border_vertical_split(self, width: float | int, height: float | int, corner_radius: float | int, border_width: float | int, left_section_width: float | int) -> bool: ...
    def draw_rounded_progress_bar_with_border(self, width: float | int, height: float | int, corner_radius: float | int, border_width: float | int, progress_value_1: float, progress_value_2: float, orientation: str) -> bool: ...
    def draw_rounded_slider_with_border_and_button(self, width: float | int, height: float | int, corner_radius: float | int, border_width: float | int, button_length: float | int, button_corner_radius: float | int, slider_value: float, orientation: str) -> bool: ...
    def draw_rounded_scrollbar(self, width: float | int, height: float | int, corner_radius: float | int, border_spacing: float | int, start_value: float, end_value: float, orientation: str) -> bool: ...
    def draw_checkmark(self, width: float | int, height: float | int, size: int | float) -> bool: ...
    def draw_dropdown_arrow(self, x_position: int | float, y_position: int | float, size: int | float) -> bool: ...
