class FontManager:
    linux_font_path: str
    @classmethod
    def init_font_manager(cls): ...
    @classmethod
    def windows_load_font(cls, font_path: str | bytes, private: bool = True, enumerable: bool = False) -> bool: ...
    @classmethod
    def load_font(cls, font_path: str) -> bool: ...
