from PIL import Image, ImageTk
from typing import Callable

class CTkImage:
    def __init__(self, light_image: Image.Image = None, dark_image: Image.Image = None, size: tuple[int, int] = (20, 20)) -> None: ...
    def add_configure_callback(self, callback: Callable): ...
    def remove_configure_callback(self, callback: Callable): ...
    def configure(self, **kwargs) -> None: ...
    def cget(self, attribute_name: str) -> any: ...
    def create_scaled_photo_image(self, widget_scaling: float, appearance_mode: str) -> ImageTk.PhotoImage: ...
