from .core_rendering import CTkCanvas as CTkCanvas, DrawEngine as DrawEngine
from .core_widget_classes import CTkBaseClass as CTkBaseClass
from .theme import ThemeManager as ThemeManager
from typing import Any

class CTkFrame(CTkBaseClass):
    def __init__(self, master: Any, width: int = 200, height: int = 200, corner_radius: int | str | None = None, border_width: int | str | None = None, bg_color: str | tuple[str, str] = 'transparent', fg_color: str | tuple[str, str] | None = None, border_color: str | tuple[str, str] | None = None, background_corner_colors: tuple[str | tuple[str, str]] | None = None, overwrite_preferred_drawing_method: str | None = None, **kwargs) -> None: ...
    def winfo_children(self) -> list[any]: ...
    def configure(self, require_redraw: bool = False, **kwargs) -> None: ...
    def cget(self, attribute_name: str) -> any: ...
    def bind(self, sequence=None, command=None, add: bool = True) -> None: ...
    def unbind(self, sequence=None, funcid=None) -> None: ...
