# pyright: reportIncompleteStub=false
from typing import Any
import tkinter as tk

def set_appearance_mode(mode_string: str) -> None: ...
def set_default_color_theme(color_string: str) -> None: ...

class CTk(tk.Tk):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class CTkButton(tk.Button):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkLabel(tk.Label):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkEntry(tk.Entry):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkFrame(tk.Frame):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...
    
class CTkToplevel(tk.Toplevel):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

# Fallback für alle weiteren Komponenten
def __getattr__(name: str) -> Any: ...