# pyright: reportIncompleteStub=false
from typing import Any, Optional, Tuple
import tkinter as tk

def set_appearance_mode(mode_string: str) -> None: ...
def get_appearance_mode() -> str: ...
def set_default_color_theme(color_string: str) -> None: ...
def set_widget_scaling(scaling_value: float) -> None: ...
def set_window_scaling(scaling_value: float) -> None: ...
def deactivate_automatic_dpi_awareness() -> None: ...

class CTk(tk.Tk):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class CTkToplevel(tk.Toplevel):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class CTkFrame(tk.Frame):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkScrollableFrame(tk.Frame):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkButton(tk.Button):
    _canvas: Any
    _text_label: Any
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...
    def configure(self, require_redraw: bool = ..., **kwargs: Any) -> None: ...

class CTkLabel(tk.Label):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...
    def configure(self, require_redraw: bool = ..., **kwargs: Any) -> None: ...

class CTkEntry(tk.Entry):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...
    def configure(self, require_redraw: bool = ..., **kwargs: Any) -> None: ...

class CTkCheckBox(tk.Checkbutton):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkRadioButton(tk.Radiobutton):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkOptionMenu(tk.Frame):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...
    def set(self, value: str) -> None: ...
    def get(self) -> str: ...
    def configure(self, require_redraw: bool = ..., **kwargs: Any) -> None: ...

class CTkComboBox(tk.Frame):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...
    def set(self, value: str) -> None: ...
    def get(self) -> str: ...
    def configure(self, require_redraw: bool = ..., **kwargs: Any) -> None: ...

class CTkFont:
    def __init__(self, family: Optional[str] = ..., size: Optional[int] = ..., weight: Optional[str] = ..., slant: Optional[str] = ..., underline: bool = ..., overstrike: bool = ...) -> None: ...

class CTkImage:
    def __init__(self, light_image: Any = ..., dark_image: Any = ..., size: Tuple[int, int] = ...) -> None: ...

class CTkTabview(tk.Frame):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...
    def add(self, name: str) -> Any: ...

class CTkTextbox(tk.Text):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkProgressBar(tk.Frame):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkSlider(tk.Frame):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkSwitch(tk.Checkbutton):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkScrollbar(tk.Scrollbar):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkSegmentedButton(tk.Frame):
    def __init__(self, master: Any = ..., **kwargs: Any) -> None: ...

class CTkInputDialog(CTkToplevel):
    def __init__(self, title: str = ..., text: str = ..., **kwargs: Any) -> None: ...
    def get_input(self) -> Optional[str]: ...

def __getattr__(name: str) -> Any: ...